const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
const {insertionDay}=require('../web/js/workspace.js');const source=fs.readFileSync('web/js/foundation.js','utf8');
function node(tag='div',className='',textContent=''){return {tag,className,textContent,children:[],events:{},dataset:{},isConnected:true,value:'',append(...v){this.children.push(...v)},prepend(...v){this.children.unshift(...v)},replaceChildren(...v){this.children=v},setAttribute(){},addEventListener(name,fn){(this.events[name]??=[]).push(fn)},fire(name,patch={}){for(const fn of this.events[name]||[])fn({target:this,...patch})},querySelector(){return null}};}
function setup(){let handler,form,reviewApply,previewDrawn;const fields=new Map(),requests=[],body=node(),dialog={open:true};const conditions={city:'tokyo',visit:{date:'2026-11-06'},party:{adults:2}};const state={epoch:1,trip:{id:'t',version:1,start_date:'2026-11-01',end_date:'2026-11-12'},discovery:{conditions:{version:2,conditions},draft:{conditions}},itineraries:{selected:new Map([['place',{place_id:'place',name:'Place',duration_minutes:60,duration_origin:'default'}]]),day:'2026-11-02'},recommendations:{displayed:null},workspaceReturn:{},intents:new Map()};
  const result={itinerary_id:'preview-itinerary',preview_id:'pv',base_version:0,state:'ready',can_apply:true,expires_at:'2026-11-01',result:{items:[{item_id:'place',local_start:'2026-11-06T12:00'}],conflicts:[]},snapshot:{start_date:'2026-11-06',activity_start:'12:00',selected:[{place_id:'place'}]}};
  let identity=0;const context=vm.createContext({state,Map,Date,Number,window:{WorkspaceUX:{insertionDay,changed(){}}},$:id=>id==='#dialog'?dialog:node(),make:node,button:(label,fn,cls)=>{const b=node('button',cls,label);b.click=fn;return b;},
    ensureDiscoveryDraft:()=>state.discovery.draft,itineraryCandidatePool:()=>new Map(state.itineraries.selected),openDialog:(_title,build)=>build(body),recommendationConditionsLabel:()=>'',
    formBase:(host,label,fn)=>{handler=fn;form=node('form');const grid=node('div');form.append(grid);host.append(form);return {form,grid};},
    field:(grid,name,label,value,options)=>{const n=node('input');n.value=String(value??'');n.dataset.field=name;grid.append(n);fields.set(name,n);return n;},reviewCheckbox:(grid,name)=>{const n=node('input');n.checked=false;fields.set(name,n);return n;},
    api:async(path,options)=>{requests.push({path,options});if(path.endsWith('/generation-previews'))return {itinerary_id:'preview-itinerary',job_id:'j'};if(path.endsWith('/generation-preview/apply'))return {itinerary_id:'preview-itinerary',active_revision_id:'rev',version:1};return result;},
    tripPath:()=>'/trips/t',itineraryId:v=>v.itinerary_id,itineraryRecommendationRef:()=>null,uid:()=> 'idempotency-'+(++identity),watchJob(){},mergeJob(){},localError(){},showError(){},terminal:j=>['succeeded','partial','failed','cancelled'].includes(j.state),renderItineraryPreview:(host,value,before,apply)=>{previewDrawn=value;reviewApply=apply},itineraryReasons(){},stageText:{},formError(){},nextAction:()=>'',dialogBusy:false,closeDialog(){dialog.open=false;},setTab(){},loadItineraries:async()=>{},loadBookings:async()=>{state.trip.version=3;},loadDiscovery:async()=>{state.discovery.conditions.version=4;},notice(){},pollJob:async()=>{},toggleItineraryPlace(){},
  });
  const start=source.indexOf('  function itineraryGenerationForm('),end=source.indexOf('  function itineraryDates(',start);vm.runInContext(source.slice(start,end),context);
  return {context,state,fields,requests,body,result,open(){context.itineraryGenerationForm({place_id:'place',name:'Place'});},submit:()=>handler(),get form(){return form},apply:()=>reviewApply(),get preview(){return previewDrawn}};
}
test('first itinerary uses exploration date, then a user-selected insertion date, independent of timeline day',()=>{const f=setup();f.open();assert.equal(f.fields.get('start_date').value,'2026-11-06');f.state.workspaceReturn.insertion_date='2026-11-09';f.open();assert.equal(f.fields.get('start_date').value,'2026-11-09');});
test('generation returns a reviewable preview without activating an itinerary; explicit apply activates it',async()=>{const f=setup();f.open();await f.submit();assert.equal(f.requests[0].path,'/trips/t/itineraries/generation-previews');assert.equal(f.state.itineraries.displayed,undefined);assert.equal(f.preview.can_apply,true);assert.equal(f.requests.some(r=>r.path.endsWith('/apply')),false);await f.apply();assert.equal(f.requests.at(-1).path,'/trips/t/itineraries/preview-itinerary/generation-preview/apply');assert.equal(f.state.itineraries.displayed.active_revision_id,'rev');assert.equal(f.state.workspaceReturn.generation_preview_id,undefined);});
test('editing after preview invalidates its apply action without discarding current form inputs',async()=>{const f=setup();f.open();await f.submit();f.fields.get('start_date').value='2026-11-08';f.form.fire('input',{target:f.fields.get('start_date')});await f.apply();assert.equal(f.requests.some(r=>r.path.endsWith('/apply')),false);assert.equal(f.fields.get('start_date').value,'2026-11-08');});
test('late preview reply after a trip change cannot become an apply target',async()=>{const f=setup();f.open();f.state.epoch++;await f.submit();assert.equal(f.preview,undefined);assert.equal(f.state.itineraries.displayed,undefined);});
function descendants(root){return root.children.flatMap(child=>[child,...descendants(child)]);}
test('expired preview can be regenerated with a new key instead of replaying the same expired result',async()=>{const f=setup();f.result.state='expired';f.result.can_apply=false;f.open();await f.submit();await f.submit();const posts=f.requests.filter(r=>r.path.endsWith('/generation-previews'));assert.equal(posts.length,2);assert.notEqual(posts[0].options.headers['Idempotency-Key'],posts[1].options.headers['Idempotency-Key']);});
test('a lost apply response recovers the already applied itinerary without another generation',async()=>{const f=setup();f.result.applied_revision_id='saved-revision';f.result.can_apply=false;f.open();await f.submit();assert.equal(f.preview,undefined);const recover=descendants(f.body).find(n=>n.textContent==='저장된 일정 열기');assert.ok(recover);await recover.click();assert.equal(f.requests.some(r=>r.path.endsWith('/apply')),false);assert.equal(f.requests.at(-1).path,'/trips/t/itineraries/preview-itinerary');assert.equal(f.state.workspaceReturn.generation_preview_id,undefined);});
test('generation 409 keeps inputs and explicitly refreshes request versions before retry',async()=>{const f=setup(),original=f.context.api;let fail=true;f.context.api=async(path,options)=>{if(fail&&path.endsWith('/generation-previews')){fail=false;const error=new Error('version conflict');error.status=409;throw error;}return original(path,options);};f.open();f.fields.get('start_date').value='2026-11-07';f.fields.get('end_date').value='2026-11-07';await assert.rejects(f.submit(),/version conflict/);const recover=descendants(f.body).find(n=>n.textContent==='최신 여행 조건 확인 · 입력 유지');assert.ok(recover);await recover.click();assert.equal(f.fields.get('start_date').value,'2026-11-07');await f.submit();const request=f.requests.find(r=>r.path.endsWith('/generation-previews'));assert.equal(request.options.body.trip_version,3);assert.equal(request.options.body.conditions_version,4);});
