/* Exercise the shipped gallery, including stale rights and independent image failures. */
const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const source=fs.readFileSync('web/js/foundation.js','utf8');
class Node {
  constructor(tag='',cls='',text=''){this.tag=tag;this.className=cls;this.textContent=text;this.children=[];this.dataset={};this.attributes={};this.events={};this.hidden=false;this.classList={add:name=>{this.className+=' '+name;}};}
  append(...nodes){this.children.push(...nodes);}
  replaceChildren(...nodes){this.children=[...nodes];}
  setAttribute(name,value){this.attributes[name]=String(value);}
  getAttribute(name){return this.attributes[name]??null;}
  addEventListener(name,fn){(this.events[name]??=[]).push(fn);}
  emit(name,event={}){for(const fn of this.events[name]||[])fn(event);}
  set src(value){this.attributes.src=value;}
  get src(){return this.attributes.src;}
}
const make=(tag,cls,text)=>new Node(tag,cls,text);
const button=(label,action,cls)=>{const n=make('button',cls,label);n.addEventListener('click',action);return n;};
function load(){const context=vm.createContext({URL,Date,Set,Number,make,button});for(const name of ['safeDiscoveryLink','placePhotoUrl','placePhotoItems','placePhotoDate','placePhotoGallery']){const start=new RegExp('^  function '+name+'\\(','m').exec(source)?.index;assert.notEqual(start,undefined,name);const next=/\n  (?:async )?function |\n  (?:const|let) |\n  \$\(/g;next.lastIndex=start+3;const end=next.exec(source)?.index??source.length;vm.runInContext(source.slice(start,end),context);}return context;}
const text=node=>[node.textContent,...node.children.map(text)].join(' ');
const all=node=>[node,...node.children.flatMap(all)];
const byClass=(node,cls)=>all(node).filter(n=>n.className.split(' ').includes(cls));
const photo=(patch={})=>({id:'photo-1',url:'https://thumb.wikimedia.org/wikipedia/commons/thumb/a/ab/Restaurant.jpg/960px-Restaurant.jpg',source_url:'https://commons.wikimedia.org/wiki/File:Restaurant.jpg',author:'Photographer',license:'CC BY-SA 4.0',license_url:'https://creativecommons.org/licenses/by-sa/4.0/',alt:'실제 식당 지점 외관',checked_at:'2026-10-06T08:00:00Z',expires_at:'2099-10-06T08:00:00Z',taken_at:'2009-03-21',width:960,height:720,...patch});
const other=()=>photo({id:'photo-2',url:'https://upload.wikimedia.org/wikipedia/commons/b/bc/Restaurant_interior.jpg',source_url:'https://commons.wikimedia.org/wiki/File:Restaurant_interior.jpg',author:'Second Photographer',alt:'실제 식당 지점 내부',taken_at:'2011'});
const place=photos=>({name:'검토한 식당',native_name:'Actual restaurant',photos,photo_status:{state:'available'}});

test('photo URLs allow approved Commons raster hosts and license documents only',()=>{const c=load();for(const host of ['thumb.wikimedia.org','upload.wikimedia.org'])assert(c.placePhotoUrl(`https://${host}/wikipedia/commons/a/ab/Restaurant.jpg`,'image'));for(const url of ['javascript:alert(1)','data:image/png;base64,x','http://upload.wikimedia.org/wikipedia/commons/a/ab/R.jpg','https://upload.wikimedia.org.evil.test/wikipedia/commons/a/ab/R.jpg','https://secret@upload.wikimedia.org/wikipedia/commons/a/ab/R.jpg','https://upload.wikimedia.org/wikipedia/commons/a/ab/R.svg','https://upload.wikimedia.org/wikipedia/commons/a/ab/R.jpg?token=secret','https://127.0.0.1/R.jpg','https://thumb.wikimedia.org/other/R.jpg'])assert.equal(c.placePhotoUrl(url,'image'),null,url);assert.equal(c.placePhotoUrl('https://evil.test/wiki/File:R.jpg','source'),null);assert.equal(c.placePhotoUrl('https://creativecommons.org/other','license'),null);assert(c.placePhotoUrl('https://creativecommons.org/publicdomain/zero/1.0/','license'));});

test('revoked, expired, malformed attribution and duplicate photos cannot become card images',()=>{const c=load(),now=Date.parse('2026-10-06T09:00:00Z');assert.equal(c.placePhotoItems({...place([photo()]),photo_status:{state:'unavailable'}},now).length,0);assert.equal(c.placePhotoItems({...place([photo()]),synthetic:true},now).length,0);for(const patch of [{expires_at:'2026-10-06T08:59:59Z'},{checked_at:'invalid'},{author:''},{license_url:'javascript:alert(1)'},{alt:''}])assert.equal(c.placePhotoItems(place([photo(patch)]),now).length,0);assert.equal(c.placePhotoItems(place([photo(),photo(),other(),photo({url:'https://upload.wikimedia.org/wikipedia/commons/c/cd/Third.jpg'})]),now).length,2);});

test('two-photo gallery initially requests only its first image and keeps rights visible',()=>{const c=load(),gallery=c.placePhotoGallery(place([photo(),other()]));const images=byClass(gallery,'place-photo-image');assert.equal(images.length,2);assert.equal(images[0].src,photo().url);assert.equal(images[1].src,undefined);assert.equal(images[0].loading,'lazy');assert.equal(images[0].decoding,'async');assert.equal(images[0].referrerPolicy,'no-referrer');assert.equal(images[0].width,960);assert.equal(images[0].height,720);assert.match(images[0].alt,/2009\. 03\. 21 촬영/);const credits=byClass(gallery,'place-photo-credits')[0];assert.match(text(credits),/Photographer/);assert.match(text(credits),/CC BY-SA 4.0/);assert.match(text(credits),/현재 모습과 다를 수/);assert.match(text(credits),/일부 잘라 표시/);const links=all(credits).filter(n=>n.tag==='a');assert.equal(links.length,2);assert(links.every(n=>n.target==='_blank'&&n.rel==='noopener noreferrer'));assert.equal(byClass(gallery,'place-photo-counter')[0].attributes['aria-live'],'polite');});

test('navigation preserves controls and provides keyboard previous/next with current attribution',()=>{const c=load(),gallery=c.placePhotoGallery(place([photo(),other()])),next=byClass(gallery,'place-photo-next')[0],nav=byClass(gallery,'place-photo-navigation')[0],slides=byClass(gallery,'place-photo-slide');next.emit('click');assert.equal(slides[0].hidden,true);assert.equal(slides[1].hidden,false);assert.equal(byClass(gallery,'place-photo-image')[1].src,other().url);assert.match(text(byClass(gallery,'place-photo-credits')[0]),/Second Photographer · 2011 촬영/);assert.equal(byClass(gallery,'place-photo-counter')[0].textContent,'2 / 2');let prevented=false;nav.emit('keydown',{key:'ArrowLeft',preventDefault(){prevented=true;}});assert.equal(prevented,true);assert.equal(slides[0].hidden,false);assert.equal(byClass(gallery,'place-photo-next')[0],next);assert.match(next.attributes['aria-label'],/다음 사진/);});

test('first-image failure retains the second actual photo and hides unnecessary navigation',()=>{const c=load(),gallery=c.placePhotoGallery(place([photo(),other()])),images=byClass(gallery,'place-photo-image');images[0].emit('error');assert.equal(images[1].src,other().url);assert.equal(byClass(gallery,'place-photo-slide')[1].hidden,false);assert.equal(byClass(gallery,'place-photo-navigation')[0].hidden,true);assert.equal(byClass(gallery,'place-photo-counter')[0].textContent,'1 / 1');assert.equal(byClass(gallery,'place-photo-unavailable')[0].hidden,true);assert.match(text(byClass(gallery,'place-photo-credits')[0]),/Second Photographer/);});

test('second-image failure does not discard the earlier valid image or its attribution',()=>{const c=load(),gallery=c.placePhotoGallery(place([photo(),other()]));byClass(gallery,'place-photo-next')[0].emit('click');byClass(gallery,'place-photo-image')[1].emit('error');assert.equal(byClass(gallery,'place-photo-slide')[0].hidden,false);assert.equal(byClass(gallery,'place-photo-unavailable')[0].hidden,true);assert.match(text(byClass(gallery,'place-photo-credits')[0]),/Photographer · 2009/);});

test('all images failing keeps the stable frame and an honest source-link fallback',()=>{const c=load(),gallery=c.placePhotoGallery(place([photo(),other()])),frame=byClass(gallery,'place-photo-frame')[0];for(const image of byClass(gallery,'place-photo-image'))image.emit('error');assert.equal(byClass(gallery,'place-photo-frame')[0],frame);assert(byClass(gallery,'place-photo-slide').every(n=>n.hidden));const fallback=byClass(gallery,'place-photo-unavailable')[0];assert.equal(fallback.hidden,false);assert.match(text(fallback),/불러오지 못했/);assert.equal(all(fallback).find(n=>n.tag==='a').href,photo().source_url);assert.equal(byClass(gallery,'place-photo-counter')[0].hidden,true);});

test('unavailable photos stay compact without fake venue imagery or download requests',()=>{const c=load(),gallery=c.placePhotoGallery(place([]));assert.equal(byClass(gallery,'place-photo-gallery-empty').length,1);assert.equal(byClass(gallery,'place-photo-image').length,0);assert.equal(byClass(gallery,'place-photo-frame').length,0);assert.match(text(gallery),/사진이 아직 없어요/);assert.equal(c.placePhotoDate(photo({taken_at:null})),'촬영일 미확인');assert.doesNotMatch(c.placePhotoDate(photo({taken_at:null})),/2026/);});

test('photo text cannot inject HTML and checking a date never claims when a photo was taken',()=>{const c=load(),payload=photo({author:'<img src=x onerror=alert(1)>',alt:'<script>alert(1)</script>',taken_at:null}),gallery=c.placePhotoGallery(place([payload]));const nodes=all(gallery);assert.equal(nodes.filter(n=>n.tag==='img').length,1);assert.equal(nodes.filter(n=>n.tag==='script').length,0);assert.equal(nodes.some(n=>n.innerHTML!==undefined),false);assert.match(text(byClass(gallery,'place-photo-credits')[0]),/촬영일 미확인/);assert.doesNotMatch(text(gallery),/2026 촬영/);});

test('curated photo manifest uses metadata the real browser can display without provider calls',()=>{const c=load(),manifest=JSON.parse(fs.readFileSync('src/discovery/restaurant_photos.json','utf8'));let photos=0;for(const entry of manifest.places){const expected=entry.photos.filter(photo=>photo.enabled);if(!expected.length)continue;const clock=Date.parse(expected[0].checked_at)+60000;const actual=c.placePhotoItems(place(expected),clock);assert.equal(actual.length,expected.length,entry.external_id);assert(actual.length<=2);photos+=actual.length;}assert(photos>0);});
