const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');const vm=require('node:vm');
function functions(file,names,globals={}){const source=fs.readFileSync(file,'utf8');let script='';for(const name of names){const re=new RegExp('^  (?:async )?function '+name+'\\(', 'm');const start=source.search(re);assert(start>=0,name);const rest=source.slice(start+3);const next=rest.search(/\n  (?:async )?function |\n  window\./);script+=source.slice(start,next<0?undefined:start+3+next)+'\n';}const c=vm.createContext({structuredClone,Number,Math,window:{},...globals});vm.runInContext(script,c);return c;}
test('failed walking route retains valid raw straight-line distance, never invents minutes',()=>{const c=functions('web/js/foundation.js',['recommendationMovement'],{reviewDate:v=>v});const text=c.recommendationMovement({kind:'estimate',straight_line_m:849.6,origin:{label:'시험 호텔'},route:{status:'unknown',duration_seconds:null}});assert.equal(text,'시험 호텔에서 직선거리 850m · 도보시간 미확인');});
test('valid zero distance is displayed, verified route is distinct from straight-line',()=>{const c=functions('web/js/foundation.js',['recommendationMovement'],{reviewDate:v=>v});assert.match(c.recommendationMovement({straight_line_m:0,route:{status:'unknown'}}),/직선거리 0m/);const text=c.recommendationMovement({straight_line_m:500,route:{status:'ok',duration_seconds:1500,mode:'walking',checked_at:'2026-10-06'}});assert.match(text,/도보 약 25분/);assert.match(text,/직선거리 500m/);assert.match(text,/확인 2026-10-06/);});
test('dinner shortcut changes visible dinner preference only, preserving required budget and review conditions',()=>{const d={conditions:{visit:{date:'2026-11-10',local_time:'12:00',timezone:'Asia/Tokyo'},budget:{amount_max:3000},required:{dietary:['vegan']},distance_filter:{kind:'walking',max_duration_minutes:10},review_strict:true},overrides:{}};const original=structuredClone(d.conditions);let changes=0;const c=functions('web/js/accommodations.js',['mutateDraft','dinner'],{context:{status:'ready'},ui:{ensureDiscoveryDraft:()=>d,draftChanged:()=>changes++,setTab(){},notice(){}}});c.dinner();assert.equal(changes,1);assert.equal(d.conditions.visit.local_time,'18:00');assert.equal(d.conditions.visit.date,original.visit.date);for(const k of ['budget','required','distance_filter','review_strict'])assert.deepEqual(d.conditions[k],original[k]);assert.equal(d.conditions.prefer_nearby,true);});
test('late automatic origin response cannot replace newly selected no-origin state',async()=>{let resolve;const draft={conditions:{origin_selection:{kind:'automatic'},visit:{date:'2026-11-10'}}};const c=functions('web/js/accommodations.js',['contextChanged'],{active:()=>({id:'trip'}),context:null,epoch:0,contextSerial:0,lastContext:'',URLSearchParams,render(){},ui:{ensureDiscoveryDraft:()=>draft,tripPath:()=>'/trips/trip',api:()=>new Promise(r=>resolve=r),fail(){}}});const first=c.contextChanged();draft.conditions.origin_selection={kind:'none'};await c.contextChanged();resolve({status:'ready',origin:{label:'old'}});await first;assert.equal(c.context.status,'missing');assert.equal(c.context.origin,null);});
test('manual label without valid coordinates remains unresolved',async()=>{const c=functions('web/js/accommodations.js',['contextChanged'],{active:()=>({id:'trip'}),context:null,epoch:0,contextSerial:0,lastContext:'',render(){},ui:{ensureDiscoveryDraft:()=>({conditions:{origin_selection:{kind:'manual'},origin:{label:'name only',latitude:null,longitude:null},visit:{date:'2026-11-10'}}})}});await c.contextChanged();assert.equal(c.context.status,'unresolved');});
test('reload catches job completion between the stay read and first job status read',async()=>{const calls=[];const c=functions('web/js/accommodations.js',['recoverJobs'],{epoch:0,items:[{job_id:'job',identity_state:'unresolved'}],pending:new Set(),timer:null,path:()=>'/trips/a/accommodations',render(){},contextChanged:async()=>{},ui:{api:async path=>{calls.push(path);return path==='/jobs/job'?{state:'succeeded'}:{items:[{job_id:'job',identity_state:'candidates'}]};},fail(){}}});await c.recoverJobs();assert.deepEqual(calls,['/jobs/job','/trips/a/accommodations']);assert.equal(c.items[0].identity_state,'candidates');});
