/* Actual UI functions: durable progress, honest candidate counts and read-only reconnection. */
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
const source=fs.readFileSync('web/js/foundation.js','utf8');
function load(names,globals={}){const context=vm.createContext({console,Set,Map,...globals});for(const name of names){const start=new RegExp('^  (?:async )?function '+name+'\\(', 'm').exec(source)?.index;assert.notEqual(start,undefined,name);const next=/\n  (?:async )?function |\n  (?:const|let) |\n  \$\(/g;next.lastIndex=start+3;const end=next.exec(source)?.index??source.length;vm.runInContext(source.slice(start,end),context);}return context;}
const budgets=new Set(['BUDGET_EXHAUSTED','PROVIDER_OUTCOME_UNKNOWN']);
function models(){return load(['recommendationCounts','recommendationProgressModel'],{budgetCodes:budgets});}
function result(groups){return {sections:{local_discovery:{items:[],needs_confirmation:[],insufficient_data:[],excluded:[],...groups}}};}
function node(tag='',cls='',text=''){return {tag,className:cls,textContent:text,dataset:{},children:[],hidden:false,attributes:{},append(...children){this.children.push(...children);},replaceChildren(...children){this.children=[...children];},setAttribute(k,v){this.attributes[k]=v;},classList:{add(){}}};}
function textContent(n){return [n.textContent,...n.children.map(textContent)].join(' ');}

test('immediate submission is visible even while the prior result is successful',()=>{const c=models();const r={submitting:true,submissionStage:'validating',active:{state:'succeeded',result:result({items:[{place_id:'old'}]})}};const m=c.recommendationProgressModel(r);assert.equal(m.state,'validating');assert.equal(m.busy,true);assert.equal(m.step,0);assert.match(m.title,/여행 조건/);assert.equal(m.count,null);});
test('running stage and count come from the job, never elapsed time or a guessed percentage',()=>{const c=models();const r={active:{state:'running',job:{stage:'constraints_and_scoring',done_count:2,total_count:8}}};const m=c.recommendationProgressModel(r);assert.equal(m.count,'장소 2 / 8건');assert.equal(m.step,1);assert.doesNotMatch(JSON.stringify(m),/%/);r.active.job={stage:'source_revalidation',done_count:0,total_count:1};assert.equal(c.recommendationProgressModel(r).step,2);r.active.job={stage:'route_snapshot',done_count:0,total_count:0};assert.equal(c.recommendationProgressModel(r).count,null);});
test('unranked places are visible candidates without becoming qualified recommendations',()=>{const c=models();const data=result({needs_confirmation:[{place_id:'a'}],insufficient_data:[{place_id:'b'}]});const counts=c.recommendationCounts(data);assert.equal(counts.qualified,0);assert.equal(counts.displayable,2);const m=c.recommendationProgressModel({active:{state:'succeeded',result:data}});assert.equal(m.state,'partial');assert.match(m.title,/살펴볼 장소 2곳/);assert.match(m.description,/아직 방문 조건을 모두 통과한 추천은 아니에요/);});
test('candidate totals deduplicate two sections and give qualified evidence priority',()=>{const c=models();const data=result({items:[{place_id:'a'}],needs_confirmation:[{place_id:'b'}],excluded:[{place_id:'a'},{place_id:'c'}]});data.sections.landmark={items:[],needs_confirmation:[{place_id:'a'}],insufficient_data:[{place_id:'b'},{place_id:'d'}]};assert.equal(JSON.stringify(c.recommendationCounts(data)),JSON.stringify({qualified:1,confirmation:1,reference:1,displayable:3,excluded:1}));});
test('empty, revoked data, cancellation and budget exhaustion have distinct recovery actions',()=>{const c=models();const empty=result({});empty.summary={empty_state:{code:'CATALOG_EMPTY',title:'이 도시 자료를 준비하고 있어요',description:'장소 링크를 저장해 주세요.'}};assert.equal(c.recommendationProgressModel({active:{state:'succeeded',result:empty}}).action,'save');assert.equal(c.recommendationProgressModel({active:{state:'cancelled'}}).action,'retry');assert.equal(c.recommendationProgressModel({active:{state:'failed',error_code:'BUDGET_EXHAUSTED'}}).action,'saved');assert.equal(c.recommendationProgressModel({active:{state:'succeeded',data_status:'stale'}}).state,'partial');assert.equal(c.recommendationProgressModel({connectionError:'NETWORK'}).state,'reconnecting');});
test('unknown submission remains an explicit read-first recovery, preserving retry keys elsewhere',()=>{const c=models();const m=c.recommendationProgressModel({requestError:{code:'REQUEST_UNCONFIRMED'}});assert.equal(m.action,'refresh');assert.match(m.description,/먼저 저장된 요청/);assert.equal(m.busy,false);});
test('progress region announces real state and does not replace unchanged cancel controls',()=>{const nodes=new Map([['#recommendationRunStatus',node()],['#applyRecommendations',node()]]);const state={trip:{id:'t'},discovery:{conditions:{}},recommendations:{active:{run_id:'r',job_id:'j',state:'running',job:{stage:'route_snapshot',done_count:2,total_count:4}}}};const c=load(['recommendationCounts','recommendationProgressModel','renderRecommendationProgress'],{state,$:id=>nodes.get(id),budgetCodes:budgets,make:node,button:(label,fn,cls)=>({...node('button',cls,label),action:fn}),appendRecommendationReasons(){}});c.renderRecommendationProgress();const host=nodes.get('#recommendationRunStatus');assert.equal(nodes.get('#applyRecommendations').attributes['aria-busy'],'true');assert.equal(nodes.get('#applyRecommendations').disabled,true);assert.equal(host.attributes['aria-live'],'polite');assert.match(textContent(host),/이동 구간 2 \/ 4건/);const first=host.children;c.renderRecommendationProgress();assert.equal(host.children,first);assert.equal(host.children[1].children.filter(n=>n.attributes['aria-current']==='step').length,1);});
test('refresh resumes a persisted job by GET and watches its existing id without submitting',async()=>{const calls=[],watched=[],timers=[];const state={session:{authenticated:true},trip:{id:'t'},epoch:1,tab:'explore',recommendations:{serial:0}};const c=load(['loadRecommendations'],{state,recommendationPollTimer:null,clearTimeout(){},setTimeout(fn,ms){timers.push({fn,ms});},tripPath:()=>'/trips/t',allPages:async()=>[{run_id:'r',state:'running'}],api:async(path,opts)=>{calls.push([path,opts?.method||'GET']);return {run_id:'r',job_id:'j',state:'running',job:{stage:'candidate_snapshot'}};},restoreRecommendationOptions(){},renderRecommendationResults(){},renderRecommendationProgress(){},watchJob:(...args)=>watched.push(args)});await c.loadRecommendations();assert.deepEqual(calls,[['/trips/t/recommendations/r','GET']]);assert.deepEqual(watched,[['j',1]]);assert.equal(timers.length,1);assert.equal(state.recommendations.active.run_id,'r');});
test('lost connection retains old results and schedules only a GET retry of the same job',async()=>{const old={run_id:'old',result:result({items:[{place_id:'p'}]})},timers=[];const state={session:{authenticated:true},trip:{id:'t'},epoch:1,tab:'explore',recommendations:{serial:0,active:{run_id:'r',state:'running'},displayed:old}};const c=load(['loadRecommendations'],{state,recommendationPollTimer:null,clearTimeout(){},setTimeout(fn,ms){timers.push({fn,ms});},tripPath:()=>'/trips/t',allPages:async()=>{throw new Error('network');},renderRecommendationProgress(){}});await assert.rejects(c.loadRecommendations({runId:'r'}),/network/);assert.equal(state.recommendations.displayed,old);assert.equal(state.recommendations.connectionError,'CONNECTION_INTERRUPTED');assert.equal(timers.length,1);assert.equal(timers[0].ms,4000);});
test('existing queued job prevents duplicate submits even when click dispatch bypasses disabled state',async()=>{let calls=0;const c=load(['applyRecommendations'],{state:{recommendations:{active:{state:'queued'}}},notice(){},api:()=>calls++});await c.applyRecommendations();assert.equal(calls,0);});

test('compact unknowns preserve the first two and live seat uncertainty outside the disclosure',()=>{const names={A:'영업시간 미확인',B:'예약인원 미확인',C:'이동시간 미확인',LIVE_AVAILABILITY_NOT_CONFIRMED:'이 날짜·인원의 잔여석은 미확인이에요'};const c=load(['appendRecommendationReasons','recommendationUnknowns'],{make:node,recommendationReasonNames:names,reviewReasonText:{}});const host=node();c.recommendationUnknowns(host,['A','B','C','LIVE_AVAILABILITY_NOT_CONFIRMED']);const visible=host.children.filter(n=>n.tag!=='details').map(textContent).join(' ');assert.match(visible,/영업시간 미확인/);assert.match(visible,/예약인원 미확인/);assert.match(visible,/잔여석은 미확인/);assert.doesNotMatch(visible,/이동시간/);const more=host.children.find(n=>n.tag==='details');assert.equal(more.open,undefined);assert.match(textContent(more),/확인할 정보 1개 더 보기/);assert.match(textContent(more),/이동시간 미확인/);});
test('collapsed unknowns retain every distinct reason, including more than six remaining details',()=>{const names=Object.fromEntries(Array.from({length:11},(_,i)=>['R'+i,'조건 '+i]));const c=load(['appendRecommendationReasons','recommendationUnknowns'],{make:node,recommendationReasonNames:names,reviewReasonText:{}});const host=node();c.recommendationUnknowns(host,[...Object.keys(names),'R0']);const more=host.children.find(n=>n.tag==='details');assert.match(textContent(more),/확인할 정보 9개 더 보기/);assert.equal(more.children.find(n=>n.tag==='ul').children.length,9);assert.match(textContent(more),/조건 10/);});

function hoursFormatter(){return load(['discoveryHoursIntervals','discoveryWeeklyHours','discoveryOpeningHours','discoveryFactValue'],{factTermNames:{},factValueLabels:{last_order:'마지막 주문',last_entry:'마지막 입장',breaks:'브레이크',intervals:'영업 구간',timezone:'시간대'}});}
test('opening hours use ordered Korean weekdays, split windows and explicit overnight labels',()=>{const c=hoursFormatter();const value={scope:'published_regular_schedule',timezone:'Europe/Madrid',weekly:{sunday:[],friday:[{start:'11:00',end:'14:30',end_day_offset:0},{start:'17:00',end:'21:30',end_day_offset:0}],monday:[{start:'22:00',end:'02:00',end_day_offset:1}]}};const text=c.discoveryFactValue(value,'opening_hours');assert.match(text,/통상 영업 안내/);assert.match(text,/시설 현지 시간 · Europe\/Madrid/);assert.match(text,/금요일: 11:00–14:30 · 17:00–21:30/);assert.match(text,/월요일: 22:00–다음 날 02:00/);assert.match(text,/일요일: 휴무/);assert(text.indexOf('월요일')<text.indexOf('금요일'));assert.doesNotMatch(text,/end_day_offset|published_regular_schedule|friday/);});
test('hours keep exceptions, breaks, order cutoff, original notes and unknown fields visible',()=>{const c=hoursFormatter();const text=c.discoveryFactValue({weekly:{'0':[{start:'09:00',end:'22:00',end_day_offset:0,last_order:'21:30',breaks:[['14:00','17:00']],custom_interval:'구간 메모'}]},exceptions:[{date:'2026-12-25',closed:true,notes:'Fermé exceptionnellement'},{date:'2026-12-26',intervals:[{start:'12:00',end:'16:00',end_day_offset:0}],last_entry:'15:00'}],notes:['Last order 30 minutes before closing.'],breaks:[['13:00','14:00']],custom_rule:{unparsed:'원문 규칙'}},'opening_hours');for(const pattern of [/마지막 주문: 21:30/,/브레이크: 14:00–17:00/,/custom_interval: 구간 메모/,/2026-12-25: 휴무/,/Fermé exceptionnellement/,/2026-12-26: 12:00–16:00/,/마지막 입장: 15:00/,/Last order 30 minutes before closing\./,/브레이크: 13:00–14:00/,/custom_rule: unparsed: 원문 규칙/])assert.match(text,pattern);});
test('all nine current official restaurant schedules render without internal weekday and offset codes',()=>{const c=hoursFormatter();const payload=JSON.parse(fs.readFileSync('docs/service-v3/data/official-restaurants-2026-10-06.json','utf8'));const facts=(payload.packs||[payload]).flatMap(pack=>pack.places).flatMap(place=>place.facts).filter(fact=>fact.field==='opening_hours');assert.equal(facts.length,9);for(const fact of facts){const text=c.discoveryFactValue(fact.value,'opening_hours');assert.match(text,/월요일:/);assert.match(text,/통상 영업 안내/);assert.doesNotMatch(text,/published_regular_schedule|end_day_offset|monday|friday/);for(const note of fact.value.notes||[])assert(text.includes(note));}});
test('missing weekday stays unknown and non-hours facts keep their ordinary fallback',()=>{const c=hoursFormatter();const text=c.discoveryFactValue({weekly:{monday:null},exceptions:[]},'opening_hours');assert.match(text,/월요일: 미확인/);assert.doesNotMatch(text,/화요일|휴무/);assert.match(text,/등록된 예외 일정 없음/);assert.equal(c.discoveryFactValue({currency:'JPY',amount_min:0},'price'),'currency: JPY\namount_min: 0');});
