const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const home=require('../web/js/home.js');
function node(){return {value:'',disabled:false,children:[],events:{},append(...v){this.children.push(...v);},replaceChildren(...v){this.children=v;},addEventListener(k,fn){this.events[k]=fn;},focus(){this.focused=true;}};}
function setup(){const nodes=new Map(),get=id=>{if(!nodes.has(id))nodes.set(id,node());return nodes.get(id);};global.document={getElementById:get};const calls=[],ui={state:{trip:{id:'a'},asking:false},setTab:tab=>calls.push(tab),submitQuestion:async q=>{calls.push(q);return true;},button:(label,fn)=>({label,fn})};home.init(ui);return {ui,calls,get};}
test('home exposes three unique permitted cards without excluded or synthetic substitutes',()=>{const p=id=>({place_id:id});const run={result:{sections:{landmark:{items:[p('a'),{...p('bad'),eligibility:'ineligible'}]},local_discovery:{items:[p('a'),p('b')]},reference:{items:[{...p('fake'),synthetic:true},{...p('deferred'),selection_status:'limit_deferred'},p('c'),p('d')]}}}};assert.deepEqual(home.previews(run).map(x=>x.place_id),['a','b','c']);assert.deepEqual(home.previews(null),[]);});
test('home question submits existing scoped AI action once and uses the main conversation',async()=>{const t=setup();t.get('homeQuestion').value='체크아웃 시간은?';t.get('homeAskForm').events.submit({preventDefault(){}});await Promise.resolve();assert.deepEqual(t.calls,['ask','체크아웃 시간은?']);assert.equal(t.get('question').value,'체크아웃 시간은?');assert.equal(t.get('homeQuestion').value,'');t.ui.state.asking=true;t.get('homeQuestion').value='두 번째';t.get('homeAskForm').events.submit({preventDefault(){}});assert.equal(t.calls.length,2);});
test('failed AI request preserves input and trip/account reset clears it',async()=>{const t=setup();t.ui.submitQuestion=async()=>false;t.get('homeQuestion').value='내 입력';t.get('homeAskForm').events.submit({preventDefault(){}});await Promise.resolve();assert.equal(t.get('homeQuestion').value,'내 입력');home.clear();assert.equal(t.get('homeQuestion').value,'');});
test('question suggestions only compose, never invoke AI automatically',()=>{const t=setup();t.get('homeAskSuggestions').children[0].fn();assert.match(t.get('homeQuestion').value,/첫날/);assert.equal(t.calls.length,0);assert.equal(t.get('homeQuestion').focused,true);});
test('deleted bookmarks do not show saved; place IDs are compared exactly',()=>{assert.equal(home.savedPlace([{input_kind:'place',input_value:'p',deleted_at:'today'}],'p'),undefined);assert.equal(home.savedPlace([{input_kind:'url',input_value:'p'}],'p'),undefined);const bookmark={matched_place_id:'p'};assert.equal(home.savedPlace([bookmark],'p'),bookmark);assert.equal(home.savedPlace([bookmark],'p2'),undefined);});

const source=fs.readFileSync('web/js/foundation.js','utf8');
function load(name,globals){const c=vm.createContext({Set,...globals});const start=new RegExp('^  (?:async )?function '+name+'\\(', 'm').exec(source).index;const next=/\n  (?:async )?function |\n  (?:const|let) |\n  \$\(/g;next.lastIndex=start+3;const end=next.exec(source)?.index??source.length;vm.runInContext(source.slice(start,end),c);return c;}
test('save guards double click, exposes pending, and preserves the new trip when old request resolves',async()=>{let finish,calls=0,renders=0,loads=0;const state={trip:{id:'a'},epoch:1};const context=load('saveRecommendedPlace',{state,renderRecommendationResults:()=>renders++,api:()=>{calls++;return new Promise(r=>finish=r);},tripPath:()=>'/trips/a',loadDiscovery:async()=>loads++,notice(){},fail(){},$:()=>node()});const first=context.saveRecommendedPlace({place_id:'p'},{run_id:'r'});assert.equal(state.savingPlaces.has('p'),true);await context.saveRecommendedPlace({place_id:'p'},{run_id:'r'});assert.equal(calls,1);state.epoch++;state.trip={id:'b'};state.savingPlaces=new Set(['new']);finish({});await first;assert.equal(loads,0);assert.equal(renders,1);assert.equal(state.savingPlaces.has('new'),true);});
test('save failure clears pending so an explicit retry is possible',async()=>{let errors=0;const state={trip:{id:'a'},epoch:1};const c=load('saveRecommendedPlace',{state,renderRecommendationResults(){},api:async()=>{throw Error('offline');},tripPath:()=>'/trips/a',loadDiscovery:async()=>{},notice(){},fail:()=>errors++,$:()=>node()});await c.saveRecommendedPlace({place_id:'p'});assert.equal(state.savingPlaces.size,0);assert.equal(errors,1);});

test('an older trip switch cannot win after a slower outgoing draft save',async()=>{const resolvers=[],state={tab:'trip',epoch:1};let clears=0;const noop=()=>{};const c=load('selectTrip',{state,window:{WorkspaceUX:{leave:()=>new Promise(r=>resolvers.push(r))}},clearScope:()=>clears++,navigationMemory:noop,renderTrip:noop,renderBookings:noop,renderDocuments:noop,resetChat:noop,renderDiscoveryConditions:noop,renderBookmarks:noop,renderRecommendationResults:noop,renderItinerary:noop});const old=c.selectTrip({id:'A'},{preserveTab:true}),latest=c.selectTrip(null,{preserveTab:true});resolvers[1]();await latest;resolvers[0]();await old;assert.equal(clears,1);assert.equal(state.trip,null);});
