const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
const source=fs.readFileSync('web/js/foundation.js','utf8');
function load(names,globals={}){const c=vm.createContext({Set,Map,...globals});for(const name of names){const start=new RegExp('^  (?:async )?function '+name+'\\(', 'm').exec(source)?.index;assert.notEqual(start,undefined);const next=/\n  (?:async )?function |\n  (?:const|let) |\n  \$\(/g;next.lastIndex=start+3;const end=next.exec(source)?.index??source.length;vm.runInContext(source.slice(start,end),c);}return c;}
test('local mail mode states no external cost and does not claim arbitrary AI understanding',()=>{const c=load(['mailAnalysisDescription']);const copy=c.mailAnalysisDescription({analysis_mode:'local'});assert.match(copy.label,/추가 비용 없음/);assert.match(copy.description,/복잡한 형식.*직접 확인/);assert.doesNotMatch(copy.label,/AI/);assert.match(c.mailAnalysisDescription({unavailable:true}).description,/유지/);});
test('failed re-extraction cannot be presented as completed local analysis',()=>{const c=load(['documentAnalysisLabel'],{statusText:{active:'이전 결과 유지'}});assert.equal(c.documentAnalysisLabel({status:'active',latest_generation:{status:'failed',parse_version:'local-mail-v1'}}),'이전 결과 유지');assert.match(c.documentAnalysisLabel({status:'needs_review',latest_generation:{status:'active',parse_version:'local-mail-v1'}}),/기본 분석 완료.*확인 필요/);});
test('persisted queued/running document job blocks duplicate reprocessing after refresh',()=>{const state={reprocessing:new Set(),jobs:new Map([['j',{state:'running',files:[{document_id:'doc'}]}]])};const c=load(['documentProcessing'],{state});assert.equal(c.documentProcessing('doc'),true);assert.equal(c.documentProcessing('other'),false);state.jobs.get('j').state='failed';assert.equal(c.documentProcessing('doc'),false);state.reprocessing.add('doc');assert.equal(c.documentProcessing('doc'),true);});
test('unsupported/empty body errors give specific recovery actions',()=>{const c=load(['fileError']);assert.match(c.fileError('LOCAL_EXTRACTION_UNSUPPORTED'),/원문은 보관.*직접 입력/);assert.match(c.fileError('MAIL_BODY_EMPTY'),/본문.*첨부 파일/);assert.match(c.fileError('PROCESSING_FAILED'),/기존 예약은 유지/);});
test('capability reply cannot cross a changed user or trip scope',async()=>{const state={epoch:1,session:{authenticated:true},mailCapabilities:null};let resolve;const response=new Promise(r=>resolve=r);const c=load(['loadMailCapabilities'],{state,api:()=>response,renderMailCapabilities(){}});const pending=c.loadMailCapabilities();state.epoch=2;resolve({analysis_mode:'ai'});await pending;assert.equal(state.mailCapabilities,null);});

test('pending and cancellation review reasons stay explicit without claiming action',()=>{const c=load(['mailReviewReasonText']);assert.match(c.mailReviewReasonText(['REQUEST_NOT_CONFIRMATION']),/확정된 예약이 아니/);assert.match(c.mailReviewReasonText(['RESERVATION_CANCELLED_REVIEW']),/실제 취소 여부를 확인/);assert.equal(c.mailReviewReasonText(['BASIC_EXTRACTION_REVIEW','unknown']), '');});

test('time conflict view compares both representations and provides a correction path',()=>{function make(tag,cls='',text=''){return {tag,text,children:[],append(...v){this.children.push(...v)},setAttribute(){}}}const c=load(['renderBookingTimeConflicts'],{make});const body=make('div');c.renderBookingTimeConflicts(body,[{side:'start',summary:{date:'2026-11-06',time:'16:00'},event_local:'2026-11-06T15:00:00'}]);const content=n=>[n.text,...n.children.map(content)].join(' ');assert.match(content(body),/16:00/);assert.match(content(body),/15:00/);assert.match(content(body),/두 값을 맞추기 전에는 일정을 확정할 수 없/);});
