const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
const discovery=require('../web/js/discovery-experience.js');const lab=require('../web/js/review-lab.js');
const review=(patch={})=>({state:'available',counts:{text_count:200,classified_count:190,unknown_count:10,local_count:150,korean_count:4},...patch});
function node(tag='div',cls='',text=''){const n={tag,className:cls,textContent:text,children:[],dataset:{},attrs:{},events:{},hidden:false,value:'',append(...kids){this.children.push(...kids);},replaceChildren(...kids){this.children=[...kids];},setAttribute(k,v){this.attrs[k]=String(v);},addEventListener(k,v){this.events[k]=v;},focus(){this.focused=true;}};n.classList={add(){},remove(){}};return n;}
function text(n){return [n.textContent,...n.children.map(text)].join(' ');}
function nodes(n){return [n,...n.children.flatMap(nodes)];}
function fixture(){const dom=new Map(['#discoveryModes','#discoveryCapability','#recommendationResults','#showReferencePlaces'].map(k=>[k,node()]));global.document={querySelector:s=>dom.get(s)||null};global.window={WorkspaceUX:{changed(){}}};const calls=[],state={epoch:1,session:{authenticated:true,user:{id:'a',role:'admin'}},discovery:{},trip:{id:'ta'}};const ui={state,api:async(p,o)=>{calls.push({p,o});return {items:[]};},make:node,button:(title,fn,cls)=>{const b=node('button',cls,title);b.events.click=fn;return b;},ensureDiscoveryDraft:()=>({conditions:{city:'tokyo'}}),appendRecommendationReasons:(host,codes)=>codes.forEach(code=>host.append(node('p','',code))),recommendationCard:item=>node('article','',item.name),reviewScope:(host,c)=>host.append(node('p','',c?.stop_reason||'기간 미확인')),reasonList:(host,codes)=>codes.forEach(code=>host.append(node('p','',code))),reviewReasons:e=>e.reason_codes||[],reviewAttribution(){},reviewDate:v=>v||'미확인',tripPath:()=>'/trips/ta',openDialog:(_t,fn)=>fn(node()),bookmarkForm(){},renderRecommendationResults(){discovery.renderMode();},setDiscoveryOverride:(...args)=>calls.push(args),field:(host,name,label,value,opts)=>{const input=node('input','',label);input.value=String(value);input.name=name;input.opts=opts;host.append(input);return input;}};discovery.init(ui);discovery.clear();return {dom,calls,state,ui};}
test('review evidence shows classified and conservative denominators separately',()=>{const x=discovery.evidenceData(review());assert.equal(x.local,150/190);assert.equal(x.korean,4/190);assert.equal(x.lower,.75);assert.equal(x.upper,.07);const copy=discovery.evidenceLines(review()).join(' ');for(const term of ['78.9%','2.1%','75%','7%','T 200','C 190','U 10'])assert(copy.includes(term),term);});
test('zero denominators stay unmeasured, and unknown does not become low Korean confidence',()=>{const zero=review({counts:{text_count:0,classified_count:0,unknown_count:0,local_count:0,korean_count:0}});assert.equal(discovery.evidenceData(zero).local,null);assert.match(discovery.evidenceLines(zero).join(' '),/미측정/);assert.doesNotMatch(discovery.evidenceLines(zero).join(' '),/0%/);const unknown=review({counts:{text_count:200,classified_count:130,unknown_count:70,local_count:120,korean_count:0}});assert.equal(discovery.evidenceData(unknown).upper,.35);assert.match(discovery.evidenceLines(unknown).join(' '),/상한 35%/);});
test('unavailable, expired, negative and inconsistent records cannot make ratios',()=>{for(const e of [review({state:'unavailable'}),review({state:'stale'}),review({counts:{text_count:200,classified_count:190,unknown_count:11,local_count:150,korean_count:4}}),review({counts:{text_count:200,classified_count:190,unknown_count:10,local_count:189,korean_count:4}}),review({counts:{text_count:-1,classified_count:0,unknown_count:-1,local_count:0,korean_count:0}})])assert.equal(discovery.evidenceData(e),null);});
test('custom criteria remain a separate group and never acquire a strict badge from UI',()=>{const groups=discovery.sectionGroups({items:[{place_id:'a',criteria_group:'default_strict'},{place_id:'b',criteria_group:'custom_criteria'}],needs_confirmation:[{place_id:'c',criteria_group:'custom_criteria'}]});assert.equal(groups.length,3);assert.equal(groups[0].items[0].place_id,'a');assert.equal(groups[1].title,'직접 설정한 기준');assert.equal(groups[2].title,'직접 설정한 기준 · 방문 전 확인');assert.equal(groups[1].items[0].strict_badge,undefined);});
test('city capability follows product gate and never equates the registry with release',()=>{const data={items:[{city:'tokyo',language_profile:{status:'available'},observed_local:{status:'unavailable'}},{city:'barcelona',observed_local:{status:'available'}}]};assert.match(discovery.capabilityState(discovery.capabilityFor(data,'tokyo')).title,/준비 중/);assert.match(discovery.capabilityState(discovery.capabilityFor(data,'barcelona')).title,/사용할 수/);assert.match(discovery.capabilityState(discovery.capabilityFor(data,'seoul')).title,/확인 중/);});
test('mode tabs keep categories independent, support keyboard and never collect',()=>{const f=fixture();discovery.renderMode();const tabs=f.dom.get('#discoveryModes').children;assert.equal(tabs.length,2);assert.equal(tabs[0].attrs['aria-selected'],'true');assert.equal(tabs[1].tabIndex,-1);let prevented=false;tabs[0].events.keydown({key:'ArrowRight',preventDefault(){prevented=true;}});assert(prevented);assert.equal(discovery.filters().discoveryMode,'landmark');assert.equal(f.calls.length,0);const group=node();discovery.quickFilters(group,{categories:['restaurant']});const chips=group.children[0].children;chips[2].events.click();assert.deepEqual(f.calls,[['categories',['cafe']]]);assert.equal(discovery.filters().discoveryMode,'landmark');});
test('local unavailable cannot hide iconic candidates, and reference stays opt in',()=>{const f=fixture(),host=node(),run={result:{sections:{local_discovery:{items:[]},landmark:{items:[{place_id:'p1',name:'공식 장소',iconic_kind:'official_landmark'}]},reference:{items:[{place_id:'p2',name:'지도 장소'}]}},section_status:{local_discovery:{state:'unavailable',reason_codes:['REVIEW_PRODUCTION_DISABLED']}}}};discovery.renderSections(host,run);assert.match(text(host),/준비하고/);assert.doesNotMatch(text(host),/공식 장소|지도 장소/);discovery.selectMode('landmark');host.replaceChildren();discovery.renderSections(host,run);assert.match(text(host),/공식 장소/);assert.doesNotMatch(text(host),/지도 장소/);discovery.selectMode('reference');host.replaceChildren();discovery.renderSections(host,run);assert.match(text(host),/주변 장소 참고하기.*지도 장소/);assert.doesNotMatch(text(host),/공식 장소/);});
test('late capabilities from user A cannot populate user B state',async()=>{const f=fixture();let release;f.ui.api=()=>new Promise(r=>release=r);const pending=discovery.loadCapabilities();f.state.epoch++;discovery.clear();release({items:[{city:'tokyo',observed_local:{status:'available'}}]});await pending;assert.equal(text(f.dom.get('#discoveryCapability')),'');});
test('quality form exposes only four numeric relaxations and ordering, never language quality gates',()=>{const f=fixture(),host=node(),inputs={};const choices=discovery.qualityFields(host,inputs,{minRating:4.2,minCount:200});assert.equal(choices.review.value(),'required');assert.equal(choices.rating.value(),'required');assert.deepEqual(Object.keys(inputs),['min_local','max_korean','min_rating','min_count','ordering']);assert.deepEqual(discovery.readQuality(inputs),{minLocal:.6,maxKorean:.1,ordering:'evidence'});assert.doesNotMatch(host.children.filter(c=>c.tag==='input').map(c=>c.name).join(','),/unknown|min_classified|quality|rights/);});
test('request always uses strict evidence, while an explicit relaxation is serialized separately',()=>{const f=fixture();f.dom.set('#recommendationMinRating',{value:'4.1'});f.dom.set('#recommendationMinCount',{value:'100'});discovery.restoreFilters({minLocal:.5,maxKorean:.2,ordering:'nearby',discoveryMode:'landmark'});const request=discovery.requestFilters();assert.equal(request.review_language_filter.required,true);assert.equal(request.review_language_filter.min_local_share,.5);assert.equal(request.review_language_filter.max_korean_share,.2);assert.equal(request.rating_filter.enabled,true);assert.equal(request.ordering_profile,'nearby');assert.deepEqual(request.review_language_filter.apply_to,['local_discovery']);});
test('admin approval requires four distinct confirmations with no unresolved branch issues',()=>{const link={status:'pending',identity_version:4,evidence:{reason_codes:[]}},yes={name:true,address:true,coordinates:true,branch:true};assert(lab.readyToApprove(link,yes));for(const key of Object.keys(yes))assert.equal(lab.readyToApprove(link,{...yes,[key]:false}),false);assert.equal(lab.readyToApprove({...link,evidence:{reason_codes:['ADDRESS_MISMATCH']}},yes),false);assert.equal(lab.readyToApprove({...link,status:'revoked'},yes),false);assert.deepEqual(lab.decideBody(link,'approved',yes),{expected_identity_version:4,decision:'approved',confirm_name:true,confirm_address:true,confirm_coordinates:true,confirm_branch:true});});
test('admin reports reject arrays and oversized files, retain zero counts for server evaluation',()=>{assert.throws(()=>lab.safeJson('[]'));assert.throws(()=>lab.safeJson(' '.repeat(65537)));assert.deepEqual(lab.safeJson('{"korean":{"tp":0,"fp":0,"fn":0}}'),{korean:{tp:0,fp:0,fn:0}});});
test('reference counts never fill qualified core totals and canonical duplicates count once',()=>{const source=fs.readFileSync('web/js/foundation.js','utf8'),start=source.indexOf('  function recommendationCounts('),end=source.indexOf('  function recommendationProgressModel(',start),ctx=vm.createContext({});vm.runInContext(source.slice(start,end),ctx);const result=ctx.recommendationCounts({sections:{local_discovery:{items:[{place_id:'a'}]},landmark:{items:[{place_id:'a'}]},reference:{items:[{place_id:'b'},{place_id:'a'}]}}});assert.equal(result.qualified,1);assert.equal(result.reference,1);assert.equal(result.displayable,2);});
test('two new assets load before foundation and no general personal API cache is introduced',()=>{const html=fs.readFileSync('web/index.html','utf8');for(const name of ['discovery-experience','review-lab'])assert(html.indexOf('/js/'+name+'.js')<html.indexOf('/js/foundation.js'));const js=fs.readFileSync('web/js/discovery-experience.js','utf8')+fs.readFileSync('web/js/review-lab.js','utf8');assert.doesNotMatch(js,/localStorage|sessionStorage|\.innerHTML\s*=/);});
test('section failures offer distinct honest next steps without inventing language zeros',()=>{const titles=new Set();for(const state of ['disabled','expired','budget_exhausted','provider_failed','quality_insufficient','criteria_not_met']){const value=discovery.sectionStateCopy('local_discovery',{state});titles.add(value.title);assert.doesNotMatch(value.title+value.note,/0%/);}assert.equal(titles.size,6);});
test('restoring a mode is a read-only view change, not a new recommendation or filter edit',()=>{const f=fixture();discovery.restoreMode('reference');assert.equal(discovery.filters().discoveryMode,'reference');assert.equal(f.calls.length,0);discovery.restoreMode('invalid');assert.equal(discovery.filters().discoveryMode,'reference');});
test('collection preview is read only until explicit submit and fences changed input',async()=>{const f=fixture(),host=node();let starts=0,current=true;f.ui.api=async(path,opts)=>{f.calls.push({path,opts});return {provider:'fake',build:'test',maximum_charge_usd:'0',limits:{max_review_records:200,max_pages:20,max_attempts_per_page:2,max_elapsed_seconds:300},budget_status:[],provider_calls:0,reservation_created:false};};lab.init(f.ui);await lab.collectionPreview(host,{place_id:'p'},async()=>{starts++;},()=>current);assert.equal(starts,0);assert.equal(f.calls.length,1);assert.equal(f.calls[0].path,'/admin/review-collection-preview');assert.match(text(host),/실제 비용 견적이 아니며/);const start=nodes(host).find(n=>n.tag==='button');current=false;await start.events.click();assert.equal(starts,0);assert.match(text(host),/입력이 바뀌/);});
test('double click on a reviewed collection preview cannot submit two paid jobs',async()=>{const f=fixture(),host=node();let starts=0,release;f.ui.api=async()=>({provider:'fake',build:'test',maximum_charge_usd:'0',limits:{},budget_status:[]});lab.init(f.ui);await lab.collectionPreview(host,{},()=>{starts++;return new Promise(r=>release=r);},()=>true);const start=nodes(host).find(n=>n.tag==='button');const first=start.events.click();await start.events.click();assert.equal(starts,1);release();await first;});
