#!/usr/bin/env python3
"""Stamp public JS/CSS content hashes in index.html. Run after editing either asset.

    python3 scripts/version_web_assets.py
    python3 scripts/version_web_assets.py --check

Query-bearing assets bypass the service worker and cannot pick up a stale public
shell cache entry. Personal API requests remain network-only.
"""
import argparse
import hashlib
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ('js/accommodations.js', 'js/foundation.js', 'js/travel-tools.js', 'js/product.js', 'js/offline-store.js', 'css/foundation.css')


def updated_index():
    index = ROOT / 'web/index.html'
    original = index.read_text()
    updated = original
    for asset in ASSETS:
        revision = hashlib.sha256((ROOT / 'web' / asset).read_bytes()).hexdigest()[:12]
        pattern = r'(["\'])/' + re.escape(asset) + r'(?:\?[^"\']*)?(["\'])'
        updated, count = re.subn(pattern, lambda m: m[1] + '/' + asset + '?v=' + revision + m[2], updated)
        if count != 1:
            raise ValueError(f'Expected exactly one index reference for {asset}; found {count}')
    return index, original, updated


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    index, original, updated = updated_index()
    worker=ROOT/'web/sw.js'
    old_worker=worker.read_text()
    versioned=['/'+a+'?v='+hashlib.sha256((ROOT/'web'/a).read_bytes()).hexdigest()[:12] for a in ASSETS]
    new_worker=re.sub(r'const VERSIONED = .*?; // Generated by version_web_assets.py', 'const VERSIONED = '+json.dumps(versioned)+'; // Generated by version_web_assets.py', old_worker)
    if args.check:
        if original != updated or old_worker != new_worker:
            parser.exit(1, 'Public asset revisions are stale. Run python3 scripts/version_web_assets.py\n')
        print('Public asset content hashes match index.html')
    else:
        index.write_text(updated)
        worker.write_text(new_worker)
        print('Stamped public JS/CSS content hashes in web/index.html')


if __name__ == '__main__':
    main()
