/* Only an explicit public shell allowlist is cacheable. Personal requests stay network-only. */
const CACHE = 'travel-inbox-public-shell-v16';
const VERSIONED = ["/js/accommodations.js?v=70220802978c", "/js/foundation.js?v=b2092c2157f6", "/js/travel-tools.js?v=babbf4751245", "/js/product.js?v=a8fe8457aace", "/js/offline-store.js?v=f2e23f13122c", "/css/foundation.css?v=20feded912e8", "/css/design-system.css?v=4d0faed42ef5"]; // Generated by version_web_assets.py
const SHELL = ['/', '/index.html', '/css/foundation.css', '/css/design-system.css', '/js/foundation.js', '/js/accommodations.js', '/js/travel-tools.js','/js/product.js', '/js/offline-store.js', '/manifest.webmanifest', '/icon.svg'];
self.addEventListener('install', event => {
  event.waitUntil(caches.open(CACHE).then(cache => cache.addAll([...SHELL,...VERSIONED])).then(() => self.skipWaiting()));
});
self.addEventListener('activate', event => {
  event.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(key => key !== CACHE).map(key => caches.delete(key)))).then(() => self.clients.claim()));
});
self.addEventListener('fetch', event => {
  const request = event.request;
  const url = new URL(request.url);
  if (request.method !== 'GET' || url.origin !== self.location.origin || (!VERSIONED.includes(url.pathname+url.search) && (url.search || !SHELL.includes(url.pathname)))) return;
  // API responses, downloads, authenticated HTML, and arbitrary new paths cannot enter this cache.
  event.respondWith(fetch(request).then(response => {
    if (response.ok && response.type === 'basic' && !response.redirected && !/private|no-store/i.test(response.headers.get('Cache-Control') || '')) {
      const copy = response.clone(); caches.open(CACHE).then(cache => cache.put(request, copy));
    }
    return response;
  }).catch(async () => (await caches.match(request)) || Response.error()));
});
