/* Only an explicit public shell allowlist is cacheable. Personal requests stay network-only. */
const CACHE = 'travel-inbox-public-shell-v26';
const VERSIONED = ["/js/discovery-flow.js?v=8b52036fc0a5", "/js/discovery-experience.js?v=13a6fe1e56ed", "/js/review-lab.js?v=7222f7d6695e", "/js/workspace.js?v=6ae42c65719a", "/js/accommodations.js?v=6d21c2198b4e", "/js/foundation.js?v=66981cb2cadf", "/js/travel-tools.js?v=babbf4751245", "/js/product.js?v=0c4bb5414da3", "/js/offline-store.js?v=f2e23f13122c", "/css/foundation.css?v=a126fd2ba73a", "/css/design-system.css?v=1efa1f85d7ab", "/icon.svg?v=4bbd16dbaddf"]; // Generated by version_web_assets.py
const SHELL = ['/js/workspace.js', '/', '/index.html', '/css/foundation.css', '/css/design-system.css', '/js/foundation.js', '/js/accommodations.js', '/js/travel-tools.js','/js/product.js', '/js/offline-store.js', '/manifest.webmanifest', '/icon.svg', '/fonts/PretendardVariable-v1.3.9.woff2'];
self.addEventListener('install', event => {
  event.waitUntil(caches.open(CACHE).then(cache => cache.addAll([...SHELL,...VERSIONED])).then(() => self.skipWaiting()));
});
self.addEventListener('activate', event => {
  event.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(key => key !== CACHE).map(key => caches.delete(key)))).then(() => self.clients.claim()));
});
self.addEventListener('fetch', event => {
  const request = event.request;
  const url = new URL(request.url);
  if (request.method !== 'GET' || url.origin !== self.location.origin || (!VERSIONED.includes(url.pathname+url.search) && (url.search || !SHELL.includes(url.pathname)))) return;
  // API responses, downloads, authenticated HTML, and arbitrary new paths cannot enter this cache.
  event.respondWith(fetch(request).then(response => {
    if (response.ok && response.type === 'basic' && !response.redirected && !/private|no-store/i.test(response.headers.get('Cache-Control') || '')) {
      const copy = response.clone(); caches.open(CACHE).then(cache => cache.put(request, copy));
    }
    return response;
  }).catch(async () => (await caches.match(request)) || Response.error()));
});
